### ISSUE TITLE
[MIGRATE] Add support for Custom Resources

### ISSUE THREAD

**Issue by TheRealAmazonKendra** [TheRealAmazonKendra/workshop-poc#3]
### Tasks
- [ ] [Update the generated schema to include service name information that we don't need to further parse in IR](https://github.com/TheRealAmazonKendra/workshop-poc/issues/4)
- [ ] Update IR to either use import instructions directly from generated schema or use Custom resource handling (to be implemented)
- [ ] Add handling to look for the prefix 'Custom::<NAME_OF_CUSTOM_RESOURCE>' that does not rely on generated schema
    - [ ] Java
    - [ ] TypeScript
    - [ ] CSharp
    - [ ] Go(?)
    - [ ] Python
- [ ] Add end to end test cases for templates that include custom resources
